export const GET_ALL_REELS_REQUEST ="GET_ALL_REELS_REQUEST";
export const GET_ALL_REELS_SUCCESS ="GET_ALL_REELS_SUCCESS";
export const GET_ALL_REELS_FAILURE ="GET_ALL_REELS_FAILURE";

export const LIKE_REELS_REQUEST ="LIKE_REELS_REQUEST";
export const LIKE_REELS_SUCCESS ="LIKE_REELS_SUCCESS";
export const LIKE_REELS_FAILURE ="LIKE_REELS_FAILURE";

export const GET_USER_REELS_REQUEST ="GET_USER_REELS_REQUEST";
export const GET_USER_REELS_SUCCESS ="GET_USER_REELS_SUCCESS";
export const GET_USER_REELS_FAILURE ="GET_USER_REELS_FAILURE";

export const CREATE_REELS_REQUEST ="CREATE_REELS_REQUEST";
export const CREATE_REELS_SUCCESS ="CREATE_REELS_SUCCESS";
export const CREATE_REELS_FAILURE ="CREATE_REELS_FAILURE";